version: '3.8'

services:
    maria1:
        image: mariadb:10.4
        ports: 
            - '3306'
        environment: 
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./maria:/var/lib/maria
            - ./backups:/backups
            - ./config/master.cnf:/etc/mysql/mariadb.conf.d/master.cnf
            - ./scripts:/scripts
    maria2:
        image: mariadb:10.4
        environment: 
            MYSQL_ROOT_PASSWORD: password
        depends_on: 
            - maria1
