{
 "title": "Promotheus panel",
 "time": { "from": "2019-10-06T17:21:46.000Z", "to": "2019-12-06T04:46:19.000Z" },
 "panels": [
  {
   "title": "Sales volumes per day",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT SUM(amount) as \"amount\", created_at as \"time\"\r\nFROM sylius_payment\r\nWHERE created_at BETWEEN \"2019-10-06 00:00:00\" AND \"2019-12-07 00:00:00\"\r\nGROUP BY DATE_FORMAT(created_at, \"%d/%m/%Y\")\r\nORDER BY created_at asc;"
    }
   ]
  },
  {
   "title": "Number of customers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(id)\nFROM sylius_customer;\n"
    }
   ]
  },
  {
   "title": "Number of payments during last week",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(created_at)\nFROM sylius_payment\nWHERE created_at BETWEEN \"2019-11-30 00:00:00\" AND \"2019-12-07 00:00:00\";"
    }
   ]
  },
  {
   "title": "Needed time for get datas",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Account Created",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,1d),\n  count(id) AS \"NB\"\nFROM sylius_customer\nGROUP BY 1\nORDER BY $__timeGroup(created_at,1d)"
    }
   ]
  },
  {
   "title": "Read operations rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{command=\"select\"}[5m])",
     "legendFormat": "{{command}} queries"
    }
   ]
  },
  {
   "title": "Total number of failed connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_connection_errors_total[5m])",
     "legendFormat": "{{error}}"
    }
   ]
  }
 ]
}